name: deploy-binboi

on:
  push:
    branches:
    - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  test-backboi:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backboi
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Test codebase
        run: go test -v ./...
      - name: Check codebase builds successfully
        run: go build -v ./...
  test-frontboi:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: frontboi
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test
  deploy-binboi:
      name: Deploy binboi
      runs-on: ubuntu-latest
      needs: [ test-frontboi, test-backboi ]
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only