name: reusable-test-frontboi

on:
  workflow_call:

jobs:
  test-frontboi:
    name: Test frontboi
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: frontboi
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test