name: test-binboi

on:
  pull_request:
    branches:
    - master
    - 'release/**'
    - 'cicd/**'
    - dev

jobs:
  test-binboi:
    uses: fuz95esi/binboi/.github/workflows/reusable-test-binboi.yaml@master