name: test-binboi

on:
  pull_request:
    branches:
    - master
    - 'release/**'
    - 'cicd/**'
    - dev

jobs:
  test-frontboi:
    uses: ./.github/workflows/reusable-test-frontboi.yaml
  test-backboi:
    uses: ./.github/workflows/reusable-test-backboi.yaml