name: test-binboi

on:
  pull_request:
    branches:
    - master
    - 'release/**'
    - 'cicd/**'
    - dev

jobs:
  test-frontboi:
    uses: fuz95esi/binboi/.github/workflows/reusable-test-frontboi.yaml@master
  test-backboi:
    uses: fuz95esi/binboi/.github/workflows/reusable-test-backboi.yaml@master